version: "3"

services:
  graphdb:
    container_name: graphdb-preload
    image: ontotext/graphdb:10.0.0

    # Load all files from ../import in repo defined in ./graphdb-repo-config.ttl
    entrypoint:  ["/bin/bash", "-c", "echo hello && /opt/graphdb/dist/bin/importrdf preload --force --recursive -q /tmp -c /opt/graphdb/graphdb-repo-config.ttl /opt/graphdb/home/graphdb-import && /opt/graphdb/dist/bin/graphdb"]

    # Preload given file to existing repository (here "demo")
    # entrypoint: [ "/opt/graphdb/dist/bin/preload", "-f", "-i", "demo", "/root/graphdb-import" ]

    environment: 
      GDB_JAVA_OPTS: >-
        -Xmx2g -Xms2g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.workbench.cors.enable=true
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=60
        -Dgraphdb.append.request.id.headers=true
        -Dreuse.vars.in.subselects=true
    volumes:
      # Change folders in the .env file or directly here
      - ./import:/opt/graphdb/home/graphdb-import
      - ./graphdb-repo.ttl:/opt/graphdb/graphdb-repo-config.ttl
    ports:
      - 7200:7200
