version: "3"

services:
  graphdb:
    container_name: graphdb-preload
    image: ontotext/graphdb:10.0.0

    # Preload ./data files and launch GraphDB on port 7210
    entrypoint:  ["/bin/bash", "-c", "echo hello && /opt/graphdb/dist/bin/importrdf preload --force --recursive -q /tmp -c /opt/graphdb/graphdb-repo-config.ttl /opt/graphdb/home/graphdb-import && /opt/graphdb/dist/bin/graphdb"]


    environment: 
      GDB_JAVA_OPTS: >-
        -Xmx2g -Xms2g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.workbench.cors.enable=true
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=60
        -Dgraphdb.append.request.id.headers=true
        -Dreuse.vars.in.subselects=true
    volumes:
      # Change folders in the .env file or directly here
      - ./data/ttlData:/opt/graphdb/home/graphdb-import
      - ./data/graphdb-repo.ttl:/opt/graphdb/graphdb-repo-config.ttl
    ports:
      - 7210:7200
