name: publish website
on: [push]

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test folder
      env:
        GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
      run: |
        cd website
        npm ci
        npm run build
        cd dist
        git config --global user.email luca.fabbian.1999@gmail.com
        git config --global user.name lucafabbian
        git init
        git add .
        git commit -am "Website updated"
        git branch -M main
        git remote add origin "https://$GITHUB_TOKEN@github.com/padovagrandtour/padovagrandtour.github.io.git"
        git push -f -u origin main
